context/Web3Context.Config.ts
libs/Graph/hooks/Tracer.ts

- Was erroring a lot when switching to kovan since I removed the webConfig
- Re add the config
- Remove extra error notifications whilst we think of a better solution when switching networks

Lmdevs 315 re add graph uri

---

components/Trade/Advanced/index.tsx
components/Trade/Basic/index.tsx
context/OrderContext.tsx

- making a trade on advanced page was getting blocked because of userTokenBalance
- add flag to track if the user is on advanced or basic trading interface

Lmdevs 320 avoid checking wallet balance

---

context/TracerContext.tsx
context/Web3Context.Config.ts
package.json
yarn.lock

- Signing was not working
- parse chainId

Parse chainId into signOrders

---

components/Trade/Advanced/TradingPanel/Account.tsx
context/TracerContext.tsx

Popups were staying open even after a successful deposit/withdraw
- propagate a callback which is fired on a successful result

Close deposit and withdraw on success

---

context/TracerContext.tsx
package.json
yarn.lock

Need to swap to signing v4
change from signingV3 to v4

Update utils version

---

components/Portfolio/Trading/MarginAccounts/index.tsx

Update notice banners to tooltips on the market accounts page
Added an example of how tooltips work upon hovering over the market names

Update leverage banner to tooltip

---

components/Trade/LeverageSlider.tsx

Style the leverage bar to match designs
Updated leverage bar styling

Update leverage bar styling

---

components/Buttons/OrderButton/index.tsx
components/General/Input/NumberInput/index.tsx
components/Trade/Advanced/TradingPanel/Inputs.tsx
components/Trade/Advanced/TradingPanel/index.tsx
components/Trade/Basic/BasicInterface1/index.tsx
components/Trade/Basic/BasicInterface2/index.tsx
components/Trade/Basic/index.tsx
components/Trade/LeverageSlider.tsx
context/OrderContext.tsx
context/TracerContext.tsx
libs/Tracer/index.tsx
package.json
yarn.lock

- Market orders were not connected to open orders
- When making market orders take the best price given

Lmdevs 345 fix market orders

---

context/TracerContext.tsx
package.json
yarn.lock

- fix ome signing
- convert created field in seconds
- update tracer-utils

Lmdevs 349 update created field

---

context/TracerContext.tsx

- Long and short were the wrong way down when creating market orders
- swap long and short check

Swap long and short

---

components/General/MarketChange/index.tsx
components/General/index.tsx
components/Nav/Navbar/index.tsx
components/OrderBook/OrderBook.tsx
components/Portfolio/Insurance/DepositHistory/index.tsx
components/Portfolio/Insurance/OpenDeposits/index.tsx
components/Portfolio/Insurance/WithdrawalHistory/index.tsx
components/Portfolio/Trading/MarginAccounts/index.tsx
components/Portfolio/Trading/TradeHistory/index.tsx
components/Portfolio/Trading/Transfers/index.tsx
components/Portfolio/index.tsx
components/Trade/Advanced/TradingPanel/Account.tsx
components/Trade/Advanced/TradingPanel/index.tsx
components/Trade/Advanced/index.tsx
libs/Tracer/index.tsx
libs/utils/converters.ts

Create a dropdown menu for selecting markets
Added a selecting market dropdown menu

Lmdevs 318 select market dropdown

---

components/Nav/Navbar/index.tsx
machines/Web3Machine.ts

It was not clear for a user when they were on the wrong network
Add a dropdown displaying when the user is connected to the wrong network

Lmdevs 317 better handle unknown network

---

components/General/Input/index.tsx
components/Trade/Basic/BasicInterface1/index.tsx
components/Trade/Basic/BasicInterface2/index.tsx
components/Trade/Basic/index.tsx
libs/Tracer/index.tsx
libs/utils/converters.ts

There was a few things wrong with my version of basic interface. Instead of updating them might as well just move to stevies version
- added amount that the user was buying and a max button

Swap to basic interface 2

---

components/Insurance/PoolHealth/Breakdown.tsx
components/Nav/Navbar/index.tsx
components/Trade/Advanced/TradingPanel/index.tsx
components/Trade/Advanced/index.tsx
pages/_app.tsx
pages/insurance/[interface].tsx
pages/portfolio/index.tsx
tailwind.config.js

Fix some alignment related issues
- Added containers
- Fixed some borders

Lmdevs 366 fix alignment

---

components/Buttons/OrderButton/index.tsx
components/Charts/LightWeightChart.tsx
components/General/Dropdown/index.tsx
components/General/index.tsx
components/Nav/Navbar/index.tsx
components/OrderBook/Orders.tsx
components/Portfolio/index.tsx
components/Trade/Advanced/TradingPanel/index.tsx
pages/_app.tsx
pages/insurance/[interface].tsx
pages/portfolio/index.tsx
pages/trade/[interface].tsx
styles/index.css

Update general bg colour
Updated background colours to #000240

Update background colours

---

components/Buttons/SlideSelect/index.tsx
components/Nav/Navbar/index.tsx
pages/_app.tsx

"Currently the switch toggle element just has two states where selected changes the BG. Declan would like it if they animated across instead"
Added "animation" for the switch on the basic trading interface (if this looks good we could apply for others)

Animate switch

---

components/Modals/Modal.tsx
components/Trade/Advanced/TradingPanel/Account.tsx
components/Trade/Advanced/TradingPanel/index.tsx
components/Trade/Advanced/index.tsx
styles/index.css

- Update designs to match kitty and declans new designs
- Move trade input above deposit/withdraw
- Change deposit and withdraw to modals

Re-structure advanced

---

components/Buttons/OrderButton/index.tsx
components/Buttons/SlideSelect/index.tsx
components/General/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput.tsx

- Update market select to fit designs
- update market/limit select
- update bg color
- change size of position select

Update market/limit select and style trading input

---

components/Nav/Navbar/index.tsx
libs/Graph/hooks/Account.ts
libs/Graph/hooks/Tracer.ts

- Graph queries were not properly filtering for results
- update queries to actually filter had the syntax wrong
- update network error index

Fix graph queries

---

components/General/index.tsx
components/Trade/Advanced/TradingPanel/Account.tsx
context/InsuranceContext.tsx
context/TracerContext.tsx
libs/Tracer/index.tsx
package.json
yarn.lock

- add an approve button before the user deposits
- Add approve button for deposit

Lmdevs 406 add approve button

---

components/Buttons/OrderButton/index.tsx
components/Insurance/Pools/index.tsx
components/Modals/InsuranceModal.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
context/InsuranceContext.tsx
context/OrderContext.tsx
context/TracerContext.tsx
libs/Graph/hooks/Account.ts

- fix little bugs
- fix insurance deposit
- fix wrong colour for short

Lmdevs 409 small bug fixes

---

components/Slider/index.tsx
components/Trade/Basic/index.tsx
package.json

Build a new leverage slider
- Created a slider template
- Added a testing slider to the basic trading interface

Lmdevs 403 build slider

---

components/Trade/Advanced/TradingPanel/Account.tsx

- section content was being cut off due to a fixed width
- remove fixed width

Remove fixed .content width

---

components/Trade/Advanced/TradingPanel/Account.tsx
context/InsuranceContext.tsx
context/OrderContext.tsx

- amounts remained when exiting the modal
- clear state on exit

Lmdevs 425 clear states after modal exit

---

components/Nav/Navbar/index.tsx

Remove portfolio page (for now)
Commented out portfolio page from Navbar

Remove portfolio page

---

components/General/Input/index.tsx
components/Insurance/PoolHealth/Breakdown.tsx
components/Insurance/Pools/index.tsx
components/Modals/InsuranceModal.tsx

Resolve a few issues related to the insurance page content
- Set dynamic names
- Checkbox onclick
- Text updates

Lmdevs 441 update insurance page content

---

components/Trade/Advanced/TradingPanel/TradingInput.tsx

Swap long/short positions, market/limit order types
Note that this only updated the UI not the states in the OME

Swap position and order type

---

components/Trade/Advanced/TradingPanel/MarketSelect.tsx

Remove market dropdown
Comment out unused market dropdown elements

Remove market dropdown

---

components/Slider/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
libs/Tracer/index.tsx
types/TracerTypes.ts

-   Reflect maxLeverage within the leverage slider
-   set max and min leverage on slider

Set max and min on slider

---

components/General/Input/SmallInput/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
context/OrderContext.tsx

-   max/best button didnt align with styles
-  add best button
- add max setters to order context
- add closure element

Lmdevs 432 fix max input buttons

---

components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/index.tsx
package.json
yarn.lock

-  update account summary
-  Add buying power to account summary
- Add postTrade details to account summary

Add buying power

---

components/General/Input/SmallInput/index.tsx
components/General/index.tsx
components/Slider/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx
components/Trade/Basic/index.tsx
context/OrderContext.tsx
context/TracerContext.tsx
libs/Tracer/index.tsx

-   Leverage slider was not effecting the trade
-  reconnect leverage slider
-  fix leverage slider default values
- add value of order amount along with leverage amount

Lmdevs 447 fix leverage slider

---

components/General/Table/index.tsx
components/Nav/SubNav/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/CustomSubNav.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
context/TracerContext.tsx
libs/Tracer/index.tsx
libs/utils/orderUtils.ts

-  Update content displayed in the positions tab
- update some overflow table things for orders and fills
- re-order order and fills
- fix calcStatus for orders
- clear balances on account disconnect

Lmdevs 451 style position orders fills

---

components/Trade/Advanced/RightPanel/AccountDetails/CustomSubNav.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
context/OMEContext.tsx
libs/Tracer/index.tsx
libs/utils/orderUtils.ts

-  Oracle price was being fetched from gasOracle
-  fix tracerLibs to fetch from oracle

Fix oraclePrice

---

components/Trade/Advanced/RightPanel/index.tsx
context/OMEContext.tsx
context/OrderContext.tsx

-   Need to show last traded price
- Add best prices for long and short
- remove setting of exposure after calcTradeExposure

Lmdevs 458 add last price

---

components/General/index.tsx
components/Modals/InsuranceModal.tsx
components/Nav/Navbar/index.tsx
components/Tooltips/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
components/Trade/Advanced/TradingPanel/Account/AccountModal.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
context/InsuranceContext.tsx
libs/utils/converters.ts

Complete tooltips for advanced trade and resolve unaddressed issues along the way.
- Added more tooltips to advanced trade
- Refactored tooltip props
- Update insurance pool heath and margin account sections
- Changed some general components
- Temporarily Removed some tooltips that are not in the spec

Lmdevs 457 tooltip misc

---

components/General/Error/index.tsx
components/General/Input/SmallInput/index.tsx
components/General/index.tsx
components/Tooltips/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
package.json
styles/index.css
yarn.lock

- new tooltips had a weird pre-load due to static build
- change back to antd tooltip
- fix typescript props
- propogate changes

Lmdevs 463 swap back tooltips

---

components/Modals/Modal.tsx

Exit modals on outside clicks
Added outside click handle and binded onclick to tracer modals

Lmdevs 426 on click outside

---

components/OrderBook/Orders.tsx
components/Tables/TradingTable.tsx
components/Trade/Advanced/TradingPanel/MarketSelect/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx
context/FactoryContext.tsx
context/OrderContext.tsx
context/TracerContext.tsx
libs/Tracer/index.tsx
libs/utils/converters.ts
package.json
yarn.lock

-  There were a few little things that I needed to fix on the front end
-  work out why calcLiquidationCost wasnt working
- add customPrecision to toApproxCurrency
- re-add market dropdown

Lmdevs 461 site maintenance

---

components/Tables/TradingTable.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
context/OMEContext.tsx
libs/Ome/index.ts
libs/Tracer/index.tsx

-  order book orders were not being displayed
- revert back from remaining
- increase size of side panel
- remove logs

L mdevs 466 order book not displaying orders

---

components/Trade/Advanced/RightPanel/index.tsx

-   overflow issues with lots of orderbook orders
-   add overflow to outside container

add overflow to container

---

components/Buttons/OrderButton/index.tsx
styles/index.css

- place order hover state was across whole width
- you could click anywhere and it would place order
- remove full width
- remove old styled

Remove full width from placeOrder

---

.github/pull_request_template.md
components/General/Error/index.tsx
components/General/Input/SmallInput/index.tsx
components/General/index.tsx
components/Tooltips/TooltipSelector/index.tsx
components/Tooltips/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
pages/_app.tsx
styles/index.css

Add Usersnap for user testing
- Added Usersnap snippets
- Refactored tooltips
- Cleaned up some code in the process

Add usersnap

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

-  fix time ago
-  multiply timestamp from graph by 1000

Fix time ago

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
context/TracerContext.tsx
context/TransactionContext.tsx
context/Web3Context.Config.ts
libs/Ome/index.ts

- Make it clearer to the user when they have just placed an order which gets instantly matched
- add popup when order is partially or fully matched

LMDEVS-468-add-popup-after-instant-match

---

components/Modals/InsuranceModal.tsx
styles/index.css

When a user makes the input field active, the placeholder text '0.0' should disappear.
- Hide input placeholder on user clicks

Hide placeholder upon clicks

---

components/FundingRateGraphic/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
libs/Tracer/index.tsx

Funding rate was currently not being read in or displayed.
- add functionality for getting funding rate
- change display to assume funding rate is already given as a raw percent and simply show it as a fixed decimal

Display Funding Rate

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

Update fills tab to fit designs
- Move 'price' column before 'amount'
- Update 'Total/Fee' to 'Fee'

Update fills tab to fit designs

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

Remove the fee value column as we are not launching with it
- Remove the fee value field

Remove fee value

---

components/General/Dropdown/index.tsx
components/General/index.tsx
components/Insurance/InsuranceModal/index.tsx

Terms of deposit should always be open by default, and should always have a background colour
- Set terms of deposit open by default
- Fix disabled button hover effect bug

Lmdevs 522 fix terms dropdown

---

components/General/Error/index.tsx
context/OrderContext.tsx

- Error was displaying before attempting to place an order
- add extra checks to errors
- update error wording

Lmdevs 489 remove deposit error when no balance

---

components/Charts/LightWeightChart.tsx
components/Trade/Advanced/RightPanel/Graphs/index.tsx

- graph data was not loading correctly
- add reset of data when input data changes

Lmedvs 388 add loading to candle graph

---

components/Charts/LightWeightChart.tsx
components/FundingRateGraphic/index.tsx
components/General/Input/SmallInput/index.tsx
components/General/MarketChange/index.tsx
components/General/Notification/index.tsx
components/General/TracerModal/index.tsx
components/General/index.tsx
components/Insurance/InsuranceModal/index.tsx
components/Insurance/PoolHealth/index.tsx
components/OrderBook/OrderBook.tsx
components/Tables/TradingTable.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
components/Trade/Advanced/RightPanel/RecentTrades/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/InterfaceSelect/index.tsx
components/Trade/Advanced/TradingPanel/MarketSelect/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Basic/index.tsx
context/OrderContext.tsx
libs/Ome/index.ts
libs/utils/converters.ts

- order book only showed shorts
- centre the book
- remove unused things
- lint

Lmdevs 485 centre order book scroll

---

components/Buttons/OrderButton/index.tsx
components/General/Error/index.tsx
components/OrderBook/OrderBook.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx
context/OMEContext.tsx
context/OrderContext.tsx
context/TracerContext.tsx
libs/Ome/index.ts
libs/utils/converters.ts
package.json
types/OrderTypes.ts
yarn.lock

- slippage calc was doing nothing
- remove fee
- add slippage calc
- create two different summaries for market and limit
- fix order book sizing

Calc slippage

---

components/Buttons/OrderButton/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

- since we are launching without account historics restyle position summary
- restyle position summary

Lmedvs 535 restyle position summary

---

components/Buttons/OrderButton/index.tsx
components/OrderBook/OrderBook.tsx
components/Tables/TradingTable.tsx
components/Trade/Advanced/RightPanel/RecentTrades/index.tsx

Order book overflows with no scrolling
- Add max-height to order book

Fix order book overflow

---

components/Trade/Advanced/TradingPanel/Account/index.tsx
context/OrderContext.tsx

- started off fixing close order issue but it seemed to resolve itself
- found this issue where buying power calc was wrong
- calculate buying power from next position not just minus order exposure

fix liquidation error

---

components/Charts/LightWeightChart.tsx
components/Charts/LightWeightWrapper.tsx
components/Trade/Advanced/RightPanel/Graphs/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
hooks/TracerHooks.ts
libs/Graph/hooks/Tracer.ts
package.json
yarn.lock

- swap over to smaller candle time
- change candle time to 15 mins
- filter by selected tracer

Lmdevs 539 update candle period

---

components/Insurance/InsuranceModal/index.tsx
components/Insurance/Pools/index.tsx
components/Tooltips/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
pages/insurance/index.tsx

Link to external docs
- Add a few links to tracer docs

Add interface links

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
components/Trade/Advanced/TradingPanel/MarketSelect/index.tsx
styles/GlobalStyles.tsx
tailwind.config.js

- wasnt quite scaling in time
- added full height to market info containers
- increase break point to 1600

adjust container widths

---

components/OrderBook/index.tsx
components/Tooltips/TooltipSelector/index.tsx
components/Tooltips/index.tsx

Add a tooltip on the term 'best' in the order book section
Add the above tip

Lmdevs 633 orderbook tooltip

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

- keep consistent language
- check the side and rename

Bid to Long ask to short

---

context/InsuranceContext.tsx

Remove tracer loading
Remove loading

Remove tracer loading

---

components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Selects.tsx
context/OrderContext.tsx

- simplify user flow
- swap market and limit

Swap market an limit

---

context/InsuranceContext.tsx
context/OMEContext.tsx
context/Web3Context.Config.ts
package.json
yarn.lock

- old contract function calls causing errors
- update trader
- update contract function calls

Fix insurance contract calls

---

components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx
components/Trade/Advanced/index.tsx

Update the order summary titles as per the designer's request
Update order summary section headings

Update order summary titles

---

components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx

Remove max for amount tab
Remove max for amount tab

Remove max for amount tab

---

components/General/Input/NumberInput/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/DoubleSidedSlider.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Selects.tsx
context/OrderContext.tsx

- few bugs with the slider when user had no position
- add multiple edge case checks for different account states

Fix slider when no position

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
context/OrderContext.tsx
libs/utils/converters.ts

- PNL on the front end was displaying nothing
- remove realised pnl
- re-add calcUnrealised calc

add calcUnrealised

---

libs/Ome/index.ts

- cancel order was not working
- remove prepended 0x from orderId

omefy orderId

---

components/Tables/TradingTable.tsx
components/Trade/Advanced/RightPanel/RecentTrades/index.tsx

- remove 1 side of recent trades to avoid duplicates
- filter out 1 side of the trade
- adjust lineheight on recent trades table

Lmdevs 537 filter recent trades

---

components/Trade/Advanced/index.tsx

Remove click to adjust button
Remove click to adjust button

Remove adjust button

---

components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx

- weird behaviour when taking the absolute value and entering into the leverage input
- remove absolute value and allow negative values

allow negative levrages

---

components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx

Prevent leverage input text being cropped and aligning to the right
- Add centre alignment for leverage input
- Remove extra padding

Update leverage input style

---

components/General/Dropdown/index.tsx
components/Insurance/InsuranceModal/index.tsx
components/Trade/Advanced/RightPanel/RecentTrades/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx

Add padding to order summary
Add padding to order summary

Add padding to order summary

---

components/Trade/Advanced/RightPanel/RecentTrades/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
context/OrderContext.tsx

- buggy slider when user had position
- handle cases where user has position

update slider when user has position

---

context/OrderContext.tsx
context/TracerContext.tsx
libs/utils/converters.ts

- js numbers was causing leftover dust
- add bignumber which tracks the value of exposure
- add bignumber toWei conversion

Lmdevs 642 remove dust with exposure

---

components/Insurance/InsuranceModal/index.tsx
components/Insurance/PoolHealth/Breakdown.tsx
context/InsuranceContext.tsx

- Insurance pool breakdown percentages was wrong
- remove user balance section
- update percentages to refer to target as opposed to liquidity
- add excess amount
- set amount to 0 on modal close
- await for approval on deposit

Update insurance pool percentages

---

components/Insurance/InsuranceModal/index.tsx
components/Insurance/PoolHealth/Breakdown.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
context/InsuranceContext.tsx
context/OrderContext.tsx

- some of the calculations were still using js exposure value causing some very small or very large outputs from BN calcs
- user exposureBN for any calculations and summaries

Lmdevs 647 remove dust in new balances

---

components/Insurance/PoolHealth/Breakdown.tsx
context/OrderContext.tsx

- differences in fair price and execution price was causing some confusion when making a trade
- calculate next balances off the expected execution price

Lmdevs 656 calc new balances from execution price

---

components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/ModifyOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx

- make the ui feel more responsive to the user
- add exposure and liquidation price previews

Lmdevs 661 update exposure and liquidation price

---

components/Insurance/PoolHealth/Breakdown.tsx
components/Insurance/PoolHealth/index.tsx
components/Insurance/Pools/index.tsx
components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
libs/utils/converters.ts

- A few numbers have too many decimal places and need to be of 2 sig figs for consistency
- Rounded numbers for a few places

Round more numbers

---

components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx

- user does not want to see all the decimal places
- fix it to 8 decimal places
- increase the leverage input just a little for when users are -xx.xx

Lmdevs 659 remove input decimals in display

---

components/Trade/Advanced/RightPanel/InsuranceInfo/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Inputs.tsx
libs/Tracer/index.tsx

- insurance funding rate was displaying dummy text
- fetch insurance funding rate from the contracts

Lmdevs 663 fix insurance funding rate

---

components/Buttons/SlideSelect/Options.tsx
components/General/Divider/index.tsx
components/General/Input/SmallInput/index.tsx
components/General/index.tsx
components/Nav/Navbar/HeaderSiteSwitcher.tsx
components/Nav/Navbar/MobileSocialLogos.tsx
components/Nav/Navbar/index.tsx
components/Portfolio/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/CustomSubNav.tsx
components/Trade/Advanced/RightPanel/index.tsx
components/Trade/Advanced/TradingPanel/Account/index.tsx
components/Trade/Advanced/TradingPanel/TradingInput/DoubleSidedSlider.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PlaceOrder.tsx
components/Trade/Advanced/TradingPanel/TradingInput/PostTradeDetails.tsx
components/Trade/Advanced/TradingPanel/TradingInput/Selects.tsx
components/Trade/Advanced/index.tsx
styles/GlobalStyles.tsx

- avoid scrolling when placing order
- reduce margin and padding on the trading panel
- adjust a few container heights

Reduce sizes on advanced trading page

---

components/Buttons/OrderButton/index.tsx
components/FundingRateGraphic/index.tsx
components/Trade/Advanced/RightPanel/AccountDetails/index.tsx

- allow users to easily close their order
- add close order button
- add close order function

Lmdevs 678 add close order

---

components/Trade/Advanced/RightPanel/index.tsx

- last trade price was using top ask
- updaet to use OME last trade price

Update last trade price

---

context/InsuranceContext.tsx
libs/Tracer/index.tsx
package.json
yarn.lock

- remove dummy data displaying on insurance page
- add actual apy calculation

Add apy-calc

---

components/OrderBook/index.tsx
components/Trade/Advanced/RightPanel/RecentTrades/index.tsx
components/Trade/Advanced/RightPanel/index.tsx
libs/utils/converters.ts

Prices need to align right not left
- Align price displays to the right
- Add a bit of padding for table headers

Price alignment

---

README.md

- add some documentation on how to run the app without having run everything locally
- add testnet .env vars to README

Add testnet env variables
